### ISSUE TITLE
Issue with docusaurus/docusaurus2 plugin

### ISSUE THREAD

**Issue by MarshHawk** [tom-grey/typedoc-plugin-markdown#104]
Hi,

Getting a fatal error with docusaurus2 and docusaurus theme that I don't get with default theme:

`Cannot read property 'replace' of undefined`

I use the following parameters:

`npx typedoc --plugin typedoc-plugin-markdown --theme docusaurus2 --excludeExternals --includeDeclarations --ignoreCompilerErrors --readme none --mode file 
--tsconfig <pathToTypesProject>/tsconfig.json --exclude **/*tests.ts --out <pathToOutDir> <pathToTypesProject>` using the types: [akumina-core](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/akumina-core)

Also, may need to look into this, so if you have any suggestions or known info, please let me know

**Comment by MarshHawk** [comment]
So, it turns out it does work without the --excludeExternals flag, but I'm getting types from all TypeScript's definitions as well... still troubleshooting

**Comment by MarshHawk** [comment]
@leoz I did share the types repo: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/akumina-core

That's all the code I have to share currently

**Comment by leoz** [comment]
@MarshHawk , thanks! Let me try it...

**Comment by leoz** [comment]
@MarshHawk , I was not able to repro.
That's what I did:

```bash
git clone https://github.com/DefinitelyTyped/DefinitelyTyped.git
cd DefinitelyTyped/
cd akumina-core/
yarn add typedoc
yarn add typedoc-plugin-markdown
npx typedoc --plugin typedoc-plugin-markdown --theme docusaurus2 --excludeExternals --includeDeclarations --ignoreCompilerErrors --readme none --mode file --tsconfig ./tsconfig.json --exclude **/*tests.ts --out ../docs .
```

**Comment by MarshHawk** [comment]
Verified that worked..., strange that it wouldn't work outside the DefinetlyTyped repo...
