### ISSUE TITLE
Ignores typedoc readme argument when set to none

### ISSUE THREAD

**Issue by dskvr** [tom-grey/typedoc-plugin-markdown#110]
The `markdown` theme produces a README despite `readme: none` typedoc argument. 

```
 --readme                  Path to the readme file that should be displayed on the index page. Pass `none` to disable the index page and start the documentation on the globals page.
```

**Comment by tom-grey** [comment]
The plugin always produces a README.md file as an entry point to the docs. (it essentially mirrors the behaviour of index.html on the default theme). With the arg --readme none set, this essentially becomes the api index page as opposed to including the contents of the specified readme. Hope that makes sense?
