### ISSUE TITLE
Can no longer use the `--readme` argument to produce a clean single-file output

### ISSUE THREAD

**Issue by motin** [tom-grey/typedoc-plugin-markdown#113]
Previously (with typedoc 0.14.2 and typedoc-plugin-markdown 1.1.21 (example [here](https://github.com/Gapminder/gsheets-gm-functions/tree/28c1f9d660fa2c3a203186b0b04b994de6d00b77))), I could use the `--readme` argument to effectively add a custom header/top section to the generate single-file markdown file, as suggested in https://github.com/TypeStrong/typedoc/issues/665.

Today, the same setup instead results in two  files being  generated: one "README.md" and one "globals.md". I have to change the `--readme` argument to `none` for a single file to be output, but it will be missing the custom header/top section. I can't use concat-md as per in https://github.com/tom-grey/typedoc-plugin-markdown/issues/59#issuecomment-511218655 since each file gets a header title added to it automatically, resulting in the concatenated file having multiple headers.

Maybe add an option `omitHeaders` so that concat-md can be used?

**Comment by tom-grey** [comment]
@motin I have made an updated so the readme will be inlined for your use case so only a single file is generated (v2.2.15). A globals file would still be required for projects that contain classes, enums and interfaces (which are compiled to their own documents). With the update one thing you would need to do is remove the title from the readme and updated the project names i.e

```
--name 'Gsheets `GM_*` Functions' 
```

Let me know if this works ok for you.
